export default {
  colors: {
    primary: '#1A2B3C',
    secondary: '#00D2B8',
    accent: '#F5A623',
    background: '#FFFFFF',
    text: '#1E293B',
    textSecondary: '#64748B',
    cardBackground: '#F5F7FA',
    subPrimary: '#033e3e',
    disabled: '#cbd5e1',
    border: '#94a3b8',
    textOnPrimary: '#ffffff',
    sent: '#E53935',
    received: '#4CAF50',
    buttonText: '#ffffff',
    disabledText: '#777',
    modalBackdrop: 'rgba(0, 0, 0, 0.5)',
    lightGray: '#777',
    mediumGray: '#666',
    white: '#fff',
    shadowColor: '#000',
  },
  fontSizes: {
    small: 12,
    medium: 14,
    large: 16,
    extraLarge: 18,
  },
  spacing: {
    small: 8,
    medium: 12,
    large: 20,
    extraLarge: 30,
  },
  borderRadius: {
    small: 8,
    medium: 10,
    large: 12,
  },
  shadow: {
    light: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 2,
    },
  },
};
