// Objective-C API for talking to github.com/BoldBitcoinWallet/BBMTLib/tss Go package.
//   gobind -lang=objc github.com/BoldBitcoinWallet/BBMTLib/tss
//
// File is generated by gobind. Do not edit.

#ifndef __Tss_H__
#define __Tss_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TssFeeResponse;
@class TssKeygenRequest;
@class TssKeygenResponse;
@class TssKeysignRequest;
@class TssKeysignResponse;
@class TssLocalState;
@class TssLocalStateAccessorImp;
@class TssLocalStateNostr;
@class TssMessage;
@class TssMessageFromTss;
@class TssMessengerImp;
@class TssServiceImpl;
@class TssSession;
@class TssStatus;
@class TssUTXO;
@class TssUTXOWithPath;
@protocol TssGoLogListener;
@class TssGoLogListener;
@protocol TssHookListener;
@class TssHookListener;
@protocol TssLocalStateAccessor;
@class TssLocalStateAccessor;
@protocol TssMessenger;
@class TssMessenger;
@protocol TssService;
@class TssService;

@protocol TssGoLogListener <NSObject>
- (void)onGoLog:(NSString* _Nullable)message;
@end

@protocol TssHookListener <NSObject>
- (void)onMessage:(NSString* _Nullable)message;
@end

@protocol TssLocalStateAccessor <NSObject>
- (NSString* _Nonnull)getLocalState:(NSString* _Nullable)pubKey error:(NSError* _Nullable* _Nullable)error;
- (BOOL)saveLocalState:(NSString* _Nullable)pubkey localState:(NSString* _Nullable)localState error:(NSError* _Nullable* _Nullable)error;
@end

@protocol TssMessenger <NSObject>
- (BOOL)send:(NSString* _Nullable)from to:(NSString* _Nullable)to body:(NSString* _Nullable)body error:(NSError* _Nullable* _Nullable)error;
@end

@protocol TssService <NSObject>
- (BOOL)applyData:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
- (TssKeygenResponse* _Nullable)keygenECDSA:(TssKeygenRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
- (TssKeysignResponse* _Nullable)keysignECDSA:(TssKeysignRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
@end

@interface TssFeeResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long fastestFee;
@property (nonatomic) long halfHourFee;
@property (nonatomic) long hourFee;
@property (nonatomic) long economyFee;
@property (nonatomic) long minimumFee;
@end

@interface TssKeygenRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull localPartyID;
@property (nonatomic) NSString* _Nonnull allParties;
@property (nonatomic) NSString* _Nonnull chainCodeHex;
// skipped method KeygenRequest.GetAllParties with unsupported parameter or return types

@end

@interface TssKeygenResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull pubKey;
@end

@interface TssKeysignRequest : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull pubKey;
@property (nonatomic) NSString* _Nonnull messageToSign;
@property (nonatomic) NSString* _Nonnull keysignCommitteeKeys;
@property (nonatomic) NSString* _Nonnull localPartyKey;
@property (nonatomic) NSString* _Nonnull derivePath;
// skipped method KeysignRequest.GetKeysignCommitteeKeys with unsupported parameter or return types

@end

@interface TssKeysignResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull msg;
@property (nonatomic) NSString* _Nonnull msgHex;
@property (nonatomic) NSString* _Nonnull r;
@property (nonatomic) NSString* _Nonnull s;
@property (nonatomic) NSString* _Nonnull derSignature;
@property (nonatomic) NSString* _Nonnull recoveryID;
@end

@interface TssLocalState : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull pubKey;
// skipped field LocalState.ECDSALocalData with unsupported type: github.com/bnb-chain/tss-lib/v2/ecdsa/keygen.LocalPartySaveData

// skipped field LocalState.KeygenCommitteeKeys with unsupported type: []string

@property (nonatomic) NSString* _Nonnull localPartyKey;
@property (nonatomic) NSString* _Nonnull chainCodeHex;
@property (nonatomic) int64_t createdAt;
@end

@interface TssLocalStateAccessorImp : NSObject <goSeqRefInterface, TssLocalStateAccessor> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)getLocalState:(NSString* _Nullable)keyshare error:(NSError* _Nullable* _Nullable)error;
- (BOOL)saveLocalState:(NSString* _Nullable)pubKey localState:(NSString* _Nullable)localState error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * LocalStateNostr wraps LocalState with the extra nostr credentials.
 */
@interface TssLocalStateNostr : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field LocalStateNostr.LocalState with unsupported type: github.com/BoldBitcoinWallet/BBMTLib/tss.LocalState

@property (nonatomic) NSString* _Nonnull nostrNpub;
@property (nonatomic) NSString* _Nonnull nsecHex;
/**
 * GetNsec returns the stored nsec by decoding from hex.
 */
- (NSString* _Nonnull)getNsec:(NSError* _Nullable* _Nullable)error;
/**
 * SetNsec stores the raw nsec as hex.
 */
- (BOOL)setNsec:(NSString* _Nullable)rawNsec error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Message structure
 */
@interface TssMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull sessionID;
@property (nonatomic) NSString* _Nonnull from;
// skipped field Message.To with unsupported type: []string

@property (nonatomic) NSString* _Nonnull body;
@property (nonatomic) NSString* _Nonnull seqNo;
@property (nonatomic) NSString* _Nonnull hash;
@end

@interface TssMessageFromTss : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable wireBytes;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) BOOL isBroadcast;
@end

@interface TssMessengerImp : NSObject <goSeqRefInterface, TssMessenger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull server;
@property (nonatomic) NSString* _Nonnull sessionID;
@property (nonatomic) NSString* _Nonnull sessionKey;
// skipped field MessengerImp.Mutex with unsupported type: sync.Mutex

- (BOOL)send:(NSString* _Nullable)from to:(NSString* _Nullable)to body:(NSString* _Nullable)body error:(NSError* _Nullable* _Nullable)error;
@end

@interface TssServiceImpl : NSObject <goSeqRefInterface, TssService> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)applyData:(NSString* _Nullable)msg error:(NSError* _Nullable* _Nullable)error;
- (TssKeygenResponse* _Nullable)keygenECDSA:(TssKeygenRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
- (TssKeysignResponse* _Nullable)keysignECDSA:(TssKeysignRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Session structure
 */
@interface TssSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull sessionID;
// skipped field Session.Participants with unsupported type: []string

@end

@interface TssStatus : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long step;
@property (nonatomic) long seqNo;
@property (nonatomic) long index;
@property (nonatomic) NSString* _Nonnull info;
@property (nonatomic) NSString* _Nonnull type;
@property (nonatomic) BOOL done;
@property (nonatomic) long time;
@end

/**
 * UTXO represents an unspent transaction output
 */
@interface TssUTXO : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull txID;
// skipped field UTXO.Vout with unsupported type: uint32

@property (nonatomic) int64_t value;
// skipped field UTXO.Status with unsupported type: struct{Confirmed bool "json:\"confirmed\""; BlockHeight int64 "json:\"block_height\""}

@end

/**
 * UTXOWithPath extends UTXO with derivation path for HD wallets (per-input signing).
 */
@interface TssUTXOWithPath : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field UTXOWithPath.UTXO with unsupported type: github.com/BoldBitcoinWallet/BBMTLib/tss.UTXO

@property (nonatomic) NSString* _Nonnull derivationPath;
@end

// skipped const MaxUint32 with unsupported type: uint32


FOUNDATION_EXPORT NSString* _Nonnull TssAesDecrypt(NSString* _Nullable encryptedData, NSString* _Nullable key, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssAesEncrypt(NSString* _Nullable data, NSString* _Nullable key, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void TssClearSessionLog(NSString* _Nullable session);

// skipped function Contains with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull TssDecodeAddress(NSString* _Nullable address, NSError* _Nullable* _Nullable error);

/**
 * DeriveNpubFromNsec derives a bech32 npub from a bech32 nsec (or hex nsec).
This function handles both bech32 (nsec1...) and hex formats.
 */
FOUNDATION_EXPORT NSString* _Nonnull TssDeriveNpubFromNsec(NSString* _Nullable partyNsec, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void TssDisableLogs(void);

FOUNDATION_EXPORT NSString* _Nonnull TssDiscoverPeers(NSString* _Nullable id_, NSString* _Nullable pubkey, NSString* _Nullable localIP, NSString* _Nullable remoteIPsCSV, NSString* _Nullable port, NSString* _Nullable timeout, NSString* _Nullable mode, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssEciesDecrypt(NSString* _Nullable encryptedData, NSString* _Nullable privateKeyHex, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssEciesEncrypt(NSString* _Nullable data, NSString* _Nullable publicKeyHex, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssEciesPubkeyFromPrivateKey(NSString* _Nullable privateKeyHex, NSError* _Nullable* _Nullable error);

/**
 * EncodeXpub encodes a public key and chain code into xpub/tpub format for watch-only wallets (Sparrow, etc.)
It derives to the BIP44 account level (m/44/0/0) so Sparrow can derive /0/x for addresses.
hexPubKey: compressed public key in hex (33 bytes / 66 chars) - the master public key
hexChainCode: chain code in hex (32 bytes / 64 chars) - the master chain code
network: "mainnet" or "testnet3"
Returns: xpub (mainnet) or tpub (testnet) encoded string at account level m/44/0/0
 */
FOUNDATION_EXPORT NSString* _Nonnull TssEncodeXpub(NSString* _Nullable hexPubKey, NSString* _Nullable hexChainCode, NSString* _Nullable network, NSError* _Nullable* _Nullable error);

/**
 * EstimateFeeWithUTXOs estimates fees using a pre-fetched UTXO pool with paths (multi-path send).
utxosWithPathsJSON: JSON array of {txid, vout, value, derivation_path or derivationPath}
changeAddress: used for change output size estimation (e.g. next HD change address)
 */
FOUNDATION_EXPORT NSString* _Nonnull TssEstimateFeeWithUTXOs(NSString* _Nullable utxosWithPathsJSON, NSString* _Nullable receiverAddress, NSString* _Nullable amountSatoshiStr, NSString* _Nullable changeAddress, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssEstimateFees(NSString* _Nullable senderAddress, NSString* _Nullable receiverAddress, int64_t amountSatoshi, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssFetchData(NSString* _Nullable url, NSString* _Nullable decKey, NSString* _Nullable data, NSError* _Nullable* _Nullable error);

// skipped function FetchUTXODetails with unsupported parameter or return types


// skipped function FetchUTXOs with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull TssGenerateKeyPair(NSError* _Nullable* _Nullable error);

// skipped function GetDERSignature with unsupported parameter or return types


// skipped function GetDerivePathBytes with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull TssGetDerivedPubKey(NSString* _Nullable hexPubKey, NSString* _Nullable hexChainCode, NSString* _Nullable path, BOOL isEdDSA, NSError* _Nullable* _Nullable error);

// skipped function GetHexEncodedPubKey with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull TssGetNetwork(NSError* _Nullable* _Nullable error);

/**
 * GetOutputDescriptor generates a wallet output descriptor for watch-only wallet import (Sparrow, etc.)
hexPubKey: compressed master public key in hex (33 bytes / 66 chars)
hexChainCode: master chain code in hex (32 bytes / 64 chars)
network: "mainnet" or "testnet3"
addressType: "legacy", "segwit-native", or "segwit-compatible"
Returns: output descriptor string (pkh for legacy, wpkh for segwit-native, sh(wpkh) for segwit-compatible)
 */
FOUNDATION_EXPORT NSString* _Nonnull TssGetOutputDescriptor(NSString* _Nullable hexPubKey, NSString* _Nullable hexChainCode, NSString* _Nullable network, NSString* _Nullable addressType, NSError* _Nullable* _Nullable error);

/**
 * GetThreshold calculates the threshold value based on the input value.
It takes an integer value as input and returns the threshold value and an error.
If the input value is negative, it returns an error with the message "invalid input".
 */
FOUNDATION_EXPORT BOOL TssGetThreshold(long value, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

// skipped function HashToInt with unsupported parameter or return types


/**
 * HexToNpub converts a hex public key to bech32 npub format.
 */
FOUNDATION_EXPORT NSString* _Nonnull TssHexToNpub(NSString* _Nullable hexKey, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void TssHook(NSString* _Nullable message);

FOUNDATION_EXPORT void TssInitLog(void);

FOUNDATION_EXPORT NSString* _Nonnull TssJoinKeygen(NSString* _Nullable ppmPath, NSString* _Nullable key, NSString* _Nullable partiesCSV, NSString* _Nullable encKey, NSString* _Nullable decKey, NSString* _Nullable session, NSString* _Nullable server, NSString* _Nullable chaincode, NSString* _Nullable sessionKey, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssJoinKeysign(NSString* _Nullable server, NSString* _Nullable key, NSString* _Nullable partiesCSV, NSString* _Nullable session, NSString* _Nullable sessionKey, NSString* _Nullable encKey, NSString* _Nullable decKey, NSString* _Nullable keyshare, NSString* _Nullable derivePath, NSString* _Nullable message, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssListenForPeers(NSString* _Nullable id_, NSString* _Nullable pubkey, NSString* _Nullable port, NSString* _Nullable timeout, NSString* _Nullable mode, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL TssLocalPreParams(NSString* _Nullable ppmFile, long timeoutMinutes, BOOL* _Nullable result, NSError* _Nullable* _Nullable error);

// skipped function Logf with unsupported parameter or return types


// skipped function Logln with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull TssMpcSendBTC(NSString* _Nullable server, NSString* _Nullable key, NSString* _Nullable partiesCSV, NSString* _Nullable session, NSString* _Nullable sessionKey, NSString* _Nullable encKey, NSString* _Nullable decKey, NSString* _Nullable keyshare, NSString* _Nullable derivePath, NSString* _Nullable publicKey, NSString* _Nullable senderAddress, NSString* _Nullable receiverAddress, int64_t amountSatoshi, int64_t estimatedFee, NSError* _Nullable* _Nullable error);

/**
 * MpcSendBTCWithUTXOs is the multi-path variant: uses pre-fetched UTXOs with per-input derivation paths.
utxosWithPathsJSON: JSON array of {txid, vout, value, derivation_path or derivationPath}
changeAddress: HD change address for change output (required)
 */
FOUNDATION_EXPORT NSString* _Nonnull TssMpcSendBTCWithUTXOs(NSString* _Nullable server, NSString* _Nullable key, NSString* _Nullable partiesCSV, NSString* _Nullable session, NSString* _Nullable sessionKey, NSString* _Nullable encKey, NSString* _Nullable decKey, NSString* _Nullable keyshare, NSString* _Nullable publicKey, NSString* _Nullable receiverAddress, NSString* _Nullable amountSatoshiStr, NSString* _Nullable estimatedFeeStr, NSString* _Nullable utxosWithPathsJSON, NSString* _Nullable changeAddress, NSError* _Nullable* _Nullable error);

/**
 * MpcSignPSBT signs a PSBT using MPC (server-based transport)
Parameters:
  - server, key, partiesCSV, session, sessionKey, encKey, decKey: TSS parameters
  - keyshare: JSON keyshare data
  - psbtBase64: base64-encoded PSBT to sign

Derivation paths and public keys are extracted from the PSBT's Bip32Derivation fields.

Returns: base64-encoded signed PSBT
 */
FOUNDATION_EXPORT NSString* _Nonnull TssMpcSignPSBT(NSString* _Nullable server, NSString* _Nullable key, NSString* _Nullable partiesCSV, NSString* _Nullable session, NSString* _Nullable sessionKey, NSString* _Nullable encKey, NSString* _Nullable decKey, NSString* _Nullable keyshare, NSString* _Nullable psbtBase64, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT TssServiceImpl* _Nullable TssNewService(id<TssMessenger> _Nullable msg, id<TssLocalStateAccessor> _Nullable stateAccessor, BOOL createPreParam, NSString* _Nullable ppmFile, NSError* _Nullable* _Nullable error);

/**
 * NostrJoinKeygen performs a Nostr-based keygen and returns the keyshare JSON.
Parameters:
  - relaysCSV: Comma-separated list of Nostr relay URLs (wss://...)
  - partyNsec: Local party's Nostr secret key (nsec1... in bech32 format)
  - partiesNpubsCSV: Comma-separated list of all party npubs (including self, in bech32 format npub1...)
  - sessionID: Session identifier
  - sessionKey: Session encryption key in hex
  - chaincode: Chain code in hex
  - ppmPath: Path to pre-params file (optional, empty string means generate new pre-params)
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrJoinKeygen(NSString* _Nullable relaysCSV, NSString* _Nullable partyNsec, NSString* _Nullable partiesNpubsCSV, NSString* _Nullable sessionID, NSString* _Nullable sessionKey, NSString* _Nullable chaincode, NSString* _Nullable ppmPath, NSError* _Nullable* _Nullable error);

/**
 * NostrJoinKeysign performs a Nostr-based keysign and returns the signature JSON.
The message will be hashed internally before signing.
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrJoinKeysign(NSString* _Nullable relaysCSV, NSString* _Nullable partyNsec, NSString* _Nullable partiesNpubsCSV, NSString* _Nullable sessionID, NSString* _Nullable sessionKey, NSString* _Nullable keyshareJSON, NSString* _Nullable derivationPath, NSString* _Nullable message, NSError* _Nullable* _Nullable error);

/**
 * NostrJoinKeysignWithSighash performs a Nostr-based keysign with a base64-encoded sighash (already a hash).
This is used for Bitcoin transaction signing where the sighash is already computed.
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrJoinKeysignWithSighash(NSString* _Nullable relaysCSV, NSString* _Nullable partyNsec, NSString* _Nullable partiesNpubsCSV, NSString* _Nullable sessionID, NSString* _Nullable sessionKey, NSString* _Nullable keyshareJSON, NSString* _Nullable derivationPath, NSString* _Nullable sighashBase64, NSError* _Nullable* _Nullable error);

/**
 * NostrKeypair generates a new Nostr keypair and returns it as JSON string.
Returns: {"nsec": "...", "npub": "..."}
Both nsec and npub are returned in bech32 format (nsec1... and npub1...)
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrKeypair(NSError* _Nullable* _Nullable error);

/**
 * NostrMpcSendBTC performs a Nostr-based MPC Bitcoin transaction.
This function is analogous to MpcSendBTC but uses Nostr transport for keysign operations.
It internally performs pre-agreement to establish sessionID and unified fees.
Parameters:
  - npubsSorted: Comma-separated sorted list of all party npubs (for sessionFlag calculation)
  - balanceSats: Balance in satoshis (for sessionFlag calculation)
  - amountSatoshi: Transaction amount in satoshis (for sessionFlag calculation)
NostrMpcSendBTC performs a Nostr-based MPC Bitcoin transaction.
changeAddress: when non-empty, change output is sent here (HD internal chain); otherwise to senderAddress.
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrMpcSendBTC(NSString* _Nullable relaysCSV, NSString* _Nullable partyNsec, NSString* _Nullable partiesNpubsCSV, NSString* _Nullable npubsSorted, NSString* _Nullable balanceSats, NSString* _Nullable keyshareJSON, NSString* _Nullable derivePath, NSString* _Nullable publicKey, NSString* _Nullable senderAddress, NSString* _Nullable receiverAddress, int64_t amountSatoshi, int64_t estimatedFee, NSString* _Nullable changeAddress, NSError* _Nullable* _Nullable error);

/**
 * NostrMpcSendBTCWithUTXOs is the multi-path variant: uses pre-fetched UTXOs with per-input derivation paths.
utxosWithPathsJSON: JSON array of {txid, vout, value, derivation_path or derivationPath}
changeAddress: HD change address for change output (required)
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrMpcSendBTCWithUTXOs(NSString* _Nullable relaysCSV, NSString* _Nullable partyNsec, NSString* _Nullable partiesNpubsCSV, NSString* _Nullable npubsSorted, NSString* _Nullable balanceSats, NSString* _Nullable keyshareJSON, NSString* _Nullable receiverAddress, NSString* _Nullable amountSatoshiStr, NSString* _Nullable estimatedFeeStr, NSString* _Nullable utxosWithPathsJSON, NSString* _Nullable changeAddress, NSError* _Nullable* _Nullable error);

/**
 * NostrMpcSignPSBT signs a PSBT using MPC over Nostr transport
This is analogous to NostrMpcSendBTC but for PSBT signing
Parameters:
  - relaysCSV: comma-separated Nostr relay URLs
  - partyNsec: party's Nostr secret key (bech32)
  - partiesNpubsCSV: comma-separated public keys of all parties (bech32)
  - npubsSorted: sorted comma-separated npubs (for sessionFlag calculation)
  - keyshareJSON: JSON keyshare data
  - psbtBase64: base64-encoded PSBT to sign

Returns: base64-encoded signed PSBT
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrMpcSignPSBT(NSString* _Nullable relaysCSV, NSString* _Nullable partyNsec, NSString* _Nullable partiesNpubsCSV, NSString* _Nullable npubsSorted, NSString* _Nullable keyshareJSON, NSString* _Nullable psbtBase64, NSError* _Nullable* _Nullable error);

/**
 * NostrPreAgreementSendBTC performs a pre-agreement phase before starting the MPC send BTC.
This is kept for backward compatibility but is now deprecated - use NostrMpcSendBTC which includes pre-agreement.
Both parties exchange their peerNonce and satoshiFees, then agree on:
- fullNonce: sorted join of both peerNonces (like in keygen)
- averageFees: average of both satoshiFees
Returns JSON: {"fullNonce": "...", "averageFees": 1234}
 */
FOUNDATION_EXPORT NSString* _Nonnull TssNostrPreAgreementSendBTC(NSString* _Nullable relaysCSV, NSString* _Nullable partyNsec, NSString* _Nullable partiesNpubsCSV, NSString* _Nullable sessionFlag, int64_t localSatoshiFees, NSError* _Nullable* _Nullable error);

/**
 * ParsePSBTDetails extracts transaction details from a PSBT for display
Returns JSON with inputs, outputs, fee, and total amounts
 */
FOUNDATION_EXPORT NSString* _Nonnull TssParsePSBTDetails(NSString* _Nullable psbtBase64, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssPostTx(NSString* _Nullable rawTxHex, NSError* _Nullable* _Nullable error);

// skipped function PreParams with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull TssPubToP2KH(NSString* _Nullable pubKeyCompressed, NSString* _Nullable mainnetORtestnet3, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssPubToP2SHP2WKH(NSString* _Nullable pubKeyCompressed, NSString* _Nullable mainnetORtestnet3, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssPubToP2TR(NSString* _Nullable pubKeyCompressedHex, NSString* _Nullable mainnetORtestnet3, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssPubToP2WPKH(NSString* _Nullable pubKeyCompressed, NSString* _Nullable mainnetORtestnet3, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssPublishData(NSString* _Nullable port, NSString* _Nullable timeout, NSString* _Nullable enckey, NSString* _Nullable data, NSString* _Nullable mode, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL TssRecommendedFees(NSString* _Nullable feeType, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * ReplaceTransaction creates a replacement transaction with a higher fee
 */
FOUNDATION_EXPORT NSString* _Nonnull TssReplaceTransaction(NSString* _Nullable server, NSString* _Nullable key, NSString* _Nullable partiesCSV, NSString* _Nullable session, NSString* _Nullable sessionKey, NSString* _Nullable encKey, NSString* _Nullable decKey, NSString* _Nullable keyshare, NSString* _Nullable derivePath, NSString* _Nullable publicKey, NSString* _Nullable senderAddress, NSString* _Nullable receiverAddress, NSString* _Nullable originalTxID, int64_t amountSatoshi, int64_t newFee, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssRunRelay(NSString* _Nullable port, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssSecP256k1Recover(NSString* _Nullable r, NSString* _Nullable s, NSString* _Nullable v, NSString* _Nullable h, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssSecureRandom(long length, NSError* _Nullable* _Nullable error);

// skipped function SelectUTXOs with unsupported parameter or return types


// skipped function SelectUTXOsWithPaths with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull TssSendBitcoin(NSString* _Nullable wifKey, NSString* _Nullable publicKey, NSString* _Nullable senderAddress, NSString* _Nullable receiverAddress, int64_t preview, int64_t amountSatoshi, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssSessionLog(NSString* _Nullable session);

FOUNDATION_EXPORT NSString* _Nonnull TssSessionState(NSString* _Nullable session);

/**
 * SetEventListener sets the listener for UTXO events
 */
FOUNDATION_EXPORT void TssSetEventListener(id<TssGoLogListener> _Nullable l);

FOUNDATION_EXPORT void TssSetHookListener(id<TssHookListener> _Nullable h);

FOUNDATION_EXPORT NSString* _Nonnull TssSetNetwork(NSString* _Nullable network, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssSha256(NSString* _Nullable msg, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssSpendingHash(NSString* _Nullable senderAddress, NSString* _Nullable receiverAddress, int64_t amountSatoshi, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssStopRelay(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssTotalUTXO(NSString* _Nullable address, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssUseAPI(NSString* _Nullable network, NSString* _Nullable base, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssUseFeeAPIs(NSString* _Nullable urls, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TssUseFeePolicy(NSString* _Nullable feeType, NSError* _Nullable* _Nullable error);

@class TssGoLogListener;

@class TssHookListener;

@class TssLocalStateAccessor;

@class TssMessenger;

@class TssService;

@interface TssGoLogListener : NSObject <goSeqRefInterface, TssGoLogListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onGoLog:(NSString* _Nullable)message;
@end

@interface TssHookListener : NSObject <goSeqRefInterface, TssHookListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onMessage:(NSString* _Nullable)message;
@end

@interface TssLocalStateAccessor : NSObject <goSeqRefInterface, TssLocalStateAccessor> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)getLocalState:(NSString* _Nullable)pubKey error:(NSError* _Nullable* _Nullable)error;
- (BOOL)saveLocalState:(NSString* _Nullable)pubkey localState:(NSString* _Nullable)localState error:(NSError* _Nullable* _Nullable)error;
@end

@interface TssMessenger : NSObject <goSeqRefInterface, TssMessenger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)send:(NSString* _Nullable)from to:(NSString* _Nullable)to body:(NSString* _Nullable)body error:(NSError* _Nullable* _Nullable)error;
@end

@interface TssService : NSObject <goSeqRefInterface, TssService> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)applyData:(NSString* _Nullable)p0 error:(NSError* _Nullable* _Nullable)error;
- (TssKeygenResponse* _Nullable)keygenECDSA:(TssKeygenRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
- (TssKeysignResponse* _Nullable)keysignECDSA:(TssKeysignRequest* _Nullable)req error:(NSError* _Nullable* _Nullable)error;
@end

#endif
