/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/BoldBitcoinWallet/BBMTLib/bbmtmobile */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "cstring.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"



#line 3 "hook_export.go"

#include <stdlib.h>
typedef void (*bbmt_hook_fn)(const char *msg);
static void bbmt_invoke_hook(bbmt_hook_fn fn, const char *msg) {
  if (fn != NULL && msg != NULL) { fn(msg); }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void BbmtFree(char* p);
extern char* DklsHelloDkg(void);
extern char* DklsVersion(void);
extern char* DklsLanJoinKeygen(char* key, char* parties, char* session, char* server, char* chaincode, char* sessionKey);
extern char* DklsNostrJoinKeygen(char* relays, char* nsec, char* peers, char* session, char* sessionKey, char* chaincode);
extern char* DklsNostrJoinKeysign(char* relays, char* nsec, char* peers, char* session, char* sessionKey, char* keyshare, char* message);
extern char* DklsMpcSignPSBT(char* server, char* key, char* parties, char* session, char* sessionKey, char* encKey, char* decKey, char* keyshare, char* psbt);
extern char* DklsNostrMpcSignPSBT(char* relays, char* nsec, char* parties, char* npubsSorted, char* keyshare, char* psbt);
extern char* DklsMpcSendBTCWithUTXOs(char* server, char* key, char* parties, char* session, char* sessionKey, char* encKey, char* decKey, char* keyshare, char* btcPub, char* toAddress, char* amount, char* fees, char* utxos, char* change);
extern char* DklsNostrMpcSendBTCWithUTXOs(char* relays, char* nsec, char* parties, char* npubsSorted, char* balance, char* keyshare, char* toAddress, char* amount, char* fees, char* utxos, char* change);
extern char* DklsCancelMpcSession(char* sessionID);
extern char* DklsCancelNostrMpc(void);
extern void DklsFree(char* p);
extern char* BbmtPublishData(char* port, char* timeout, char* enckey, char* data, char* mode);
extern char* BbmtFetchData(char* url, char* decKey, char* data);
extern char* BbmtSetNetwork(char* network);
extern char* BbmtGetNetwork(void);
extern char* BbmtSpendingHash(char* sender, char* receiver, long long amount);
extern char* BbmtSpendingHashWithUTXOs(char* utxos, char* receiver, char* amount);
extern char* BbmtEstimateFees(char* sender, char* receiver, long long amount);
extern char* BbmtEstimateFeeWithUTXOs(char* utxos, char* receiver, char* amount, char* change);
extern char* BbmtRunRelay(char* port);
extern char* BbmtStopRelay(void);
extern char* BbmtListenForPeers(char* id, char* pubkey, char* port, char* timeout, char* mode);
extern char* BbmtDiscoverPeers(char* id, char* pubkey, char* localIP, char* remoteIPs, char* port, char* timeout, char* mode);
extern char* BbmtGenerateKeyPair(void);
extern char* BbmtAesEncrypt(char* data, char* key);
extern char* BbmtAesDecrypt(char* data, char* key);
extern char* BbmtSha256(char* msg);
extern char* BbmtSecP256k1Recover(char* r, char* s, char* v, char* h);
extern char* BbmtGetDerivedPubKey(char* hexPub, char* hexChain, char* path, int isEdDSA);
extern char* BbmtEncodeXpub(char* hexPub, char* hexChain, char* network);
extern char* BbmtGetOutputDescriptor(char* hexPub, char* hexChain, char* network, char* addressType);
extern char* BbmtPubToP2WPKH(char* pub, char* network);
extern char* BbmtPubToP2SHP2WKH(char* pub, char* network);
extern char* BbmtPubToP2TR(char* pub, char* network);
extern char* BbmtPubToP2KH(char* pub, char* network);
extern char* BbmtUseFeePolicy(char* policy);
extern char* BbmtUseAPI(char* network, char* base);
extern char* BbmtUseFeeAPIs(char* urls);
extern char* BbmtTotalUTXO(char* address);
extern char* BbmtLocalPreParams(char* ppmFile, long timeoutMinutes);
extern char* BbmtJoinKeygen(char* ppmPath, char* key, char* parties, char* encKey, char* decKey, char* session, char* server, char* chaincode, char* sessionKey);
extern char* BbmtNostrKeypair(void);
extern char* BbmtHexToNpub(char* hexKey);
extern char* BbmtNostrJoinKeygen(char* relays, char* nsec, char* peers, char* session, char* sessionKey, char* chaincode, char* ppmPath);
extern char* BbmtNostrJoinKeysign(char* relays, char* nsec, char* peers, char* session, char* sessionKey, char* keyshare, char* derivePath, char* message);
extern char* BbmtPostTx(char* rawTx);
extern char* BbmtComputeTxId(char* rawTx);
extern char* BbmtCancelMpcSession(char* sessionID);
extern char* BbmtCancelNostrMpc(void);
extern void BbmtDisableLogs(void);
extern char* BbmtParsePSBTDetails(char* psbt);
extern char* BbmtMpcSignPSBT(char* server, char* key, char* parties, char* session, char* sessionKey, char* encKey, char* decKey, char* keyshare, char* psbt);
extern char* BbmtMpcSendBTCWithUTXOs(char* server, char* key, char* parties, char* session, char* sessionKey, char* encKey, char* decKey, char* keyshare, char* btcPub, char* receiver, char* amount, char* fees, char* utxos, char* change);
extern char* BbmtNostrMpcSendBTCWithUTXOs(char* relays, char* nsec, char* parties, char* npubsSorted, char* balance, char* keyshare, char* receiver, char* amount, char* fees, char* utxos, char* change);
extern char* BbmtNostrMpcSignPSBT(char* relays, char* nsec, char* parties, char* npubsSorted, char* keyshare, char* psbt);
extern void BbmtSetHookListener(bbmt_hook_fn fn);
extern void BbmtSetGoLogListener(bbmt_hook_fn fn);

#ifdef __cplusplus
}
#endif
