# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Force-enable New Architecture for CocoaPods environment
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BoldWallet' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => true,
    :new_arch_enabled => true,
  )

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-biometrics', :path => '../node_modules/react-native-biometrics'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNShare',  :path => '../node_modules/react-native-share'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  pod 'VisionCamera', :path => '../node_modules/react-native-vision-camera'
  pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  
  target 'BoldWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # fmt 11.0.2 (RCT-Folly): Apple Clang 21+ (Xcode 26.x) rejects consteval in format-inl.h.
    # fmt 12.1+ fixes this; until RN bumps fmt, disable consteval for those toolchains only.
    # https://github.com/fmtlib/fmt/issues/4740
    fmt_base = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      contents = File.read(fmt_base)
      needle = <<~PATCH.chomp
        #elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L
        #  define FMT_USE_CONSTEVAL 0  // consteval is broken in Apple clang < 14.
        #elif FMT_MSC_VERSION && FMT_MSC_VERSION < 1929
      PATCH
      insert = <<~PATCH.chomp
        #elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L
        #  define FMT_USE_CONSTEVAL 0  // consteval is broken in Apple clang < 14.
        #elif defined(__apple_build_version__) && __apple_build_version__ >= 21000000
        #  define FMT_USE_CONSTEVAL 0  // Apple clang 21+ / Xcode 26+ (fmtlib/fmt#4740)
        #elif FMT_MSC_VERSION && FMT_MSC_VERSION < 1929
      PATCH
      if contents.include?('__apple_build_version__ >= 21000000')
        # already patched
      elsif contents.include?(needle)
        File.chmod(0o644, fmt_base)
        File.write(fmt_base, contents.sub(needle, insert))
        Pod::UI.puts 'Patched Pods/fmt/include/fmt/base.h for Apple Clang 21+ (FMT_USE_CONSTEVAL=0)'.green
      else
        Pod::UI.warn 'fmt base.h patch skipped: expected preprocessor block not found (fmt version changed?)'
      end
    end
  end
end
