#!/usr/bin/env python3
"""
Copy the system clipboard text from one Android device to another via adb.

Uses `cmd clipboard get-text` / `set-text` (API 29+). Run after an app on the
source device has placed text on the clipboard (Maestro cannot read another
device's in-app clipboard without going through adb).

Optional `--write-maestro-snippet`: writes a tiny Maestro flow that uses `setClipboard`
with the same payload. Maestro's `pasteText` only reads Maestro's *internal*
clipboard, not the OS clipboard set by adb — so flows must `runFlow` this snippet
immediately before `pasteText` on the target device.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys


def write_maestro_clipboard_snippet(path: str, text: str, app_id: str) -> None:
    # json.dumps yields a YAML-safe double-quoted scalar for setClipboard.
    body = (
        f"# Auto-generated by sync_clipboard_adb.py — do not commit.\n"
        f"appId: {app_id}\n"
        f"---\n"
        f"- setClipboard: {json.dumps(text)}\n"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)


def main() -> int:
    p = argparse.ArgumentParser(description="Sync clipboard from adb device A to B.")
    p.add_argument("from_serial", help="Source device serial (e.g. emulator-5554)")
    p.add_argument("to_serial", help="Target device serial (e.g. emulator-5556)")
    p.add_argument(
        "--write-maestro-snippet",
        metavar="PATH",
        help="Write a one-step Maestro flow (setClipboard) for use before pasteText on the target device",
    )
    p.add_argument(
        "--app-id",
        default="com.boldwallet",
        help="appId embedded in the Maestro snippet (default: com.boldwallet)",
    )
    args = p.parse_args()

    get = subprocess.run(
        ["adb", "-s", args.from_serial, "exec-out", "cmd", "clipboard", "get-text"],
        capture_output=True,
    )
    if get.returncode != 0:
        sys.stderr.write(
            "adb clipboard get-text failed (need API 29+ / cmd clipboard).\n"
            f"stderr: {get.stderr.decode(errors='replace')!r}\n"
        )
        return 1

    text = get.stdout.decode("utf-8", errors="replace").rstrip("\r\n")

    setp = subprocess.run(
        ["adb", "-s", args.to_serial, "shell", "cmd", "clipboard", "set-text", text],
        capture_output=True,
    )
    if setp.returncode != 0:
        sys.stderr.write(
            "adb clipboard set-text failed.\n"
            f"stderr: {setp.stderr.decode(errors='replace')!r}\n"
        )
        return 1

    if args.write_maestro_snippet:
        write_maestro_clipboard_snippet(args.write_maestro_snippet, text, args.app_id)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
